require("visual")
require("maps")
require("defaults")
require("hooks.oil")
require("hooks.on-opening-file")
require("plugins.oil")
require("plugins.yazi")
require("plugins.which-key")
require("plugins.telescope")
require("plugins.nvim-web-devicons")

