require("defaults")
require("maps")

require("visual.color")
require("visual.ui")
require("visual.noice")
require("visual.diagnostics")
require("visual.lualine")

require("plugins.nvim-lspconfig")
require("plugins.oil")
require("plugins.yazi")
require("plugins.which-key")
require("plugins.telescope")
require("plugins.multicursor")
require("plugins.nvim-web-devicons")
require("plugins.nvim-ufo")
