require("defaults")
require("maps")
require("optimizations")

require("visual.color")
require("visual.ui")
require("visual.noice")
require("visual.diagnostics")
require("visual.statusbar")
require("visual.icons")
require("visual.dropbar")

require("plugins.nvim-lspconfig")
require("plugins.yazi")
require("plugins.which-key")
require("plugins.snacks")
require("plugins.multicursor")
require("plugins.nvim-ufo")
require("plugins.nvim-treesitter")

require("plugins.gitsigns")
require("plugins.nvim-autopairs")
require("plugins.blink")
require("plugins.toggleterm")

require("plugins.conform")
require("plugins.grapple")
